services:
  bill-manager:
    image: ghcr.io/jonb-dev/bill-mgr:latest
    x-runtipi:
      is_main: true
      internal_port: 5100
    environment:
      RP_ID: ${RP_ID}
      RP_ORIGIN: ${RP_ORIGIN}
      REGISTRATION_SECRET: ${REGISTRATION_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    restart: unless-stopped

x-runtipi:
  schema_version: 2
