services:
  bill-manager:
    image: ghcr.io/jonb-dev/bill-mgr:latest
    restart: unless-stopped
    environment:
      - RP_ID=${RP_ID}
      - RP_ORIGIN=${RP_ORIGIN}
      - REGISTRATION_SECRET=${REGISTRATION_SECRET}
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    x-runtipi:
      is_main: true
      internal_port: 5100

x-runtipi:
  schema_version: 2
